version: '3.8'

services:
  qr-esp32-web:
    image: python:3.9-slim
    container_name: qr_esp32_ota_server
    volumes:
      - qr_data:/app
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    working_dir: /app
    command: ["bash", "/usr/local/bin/entrypoint.sh"]
    ports:
      - "8000:8000"
    networks:
      - qr_network
    restart: unless-stopped

volumes:
  qr_data:
    name: qr_data

networks:
  qr_network:
    name: qr_network
    driver: bridge