version: '3'

services:
  ota-server:
    image: python:3
    container_name: ota-server
    ports:
      - "80:80"
    volumes:
      - ota-data:/data
      # Map the local entrypoint script into the container
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    working_dir: /data # Keep working dir as /data as git clones there
    # Set the entrypoint script to be executed
    entrypoint: ["/bin/bash", "/usr/local/bin/entrypoint.sh"]
    # The command is now executed by the entrypoint script
    # command: >
    #   /bin/bash -c " ... complex script removed ... "
    restart: unless-stopped

volumes:
  ota-data:
    driver: local 